version: '3.8'

services:
  car-rental-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=file:./prisma/dev.db
      - NEXTAUTH_URL=http://localhost:3000
      # Override these in .env.local or docker-compose.override.yml
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-your-nextauth-secret-here}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:-}
      - EMAIL_SERVER_USER=${EMAIL_SERVER_USER:-}
      - EMAIL_SERVER_PASSWORD=${EMAIL_SERVER_PASSWORD:-}
      - EMAIL_SERVER_HOST=${EMAIL_SERVER_HOST:-smtp.gmail.com}
      - EMAIL_SERVER_PORT=${EMAIL_SERVER_PORT:-587}
      - EMAIL_FROM=${EMAIL_FROM:-}
    volumes:
      # Mount the source code for development (hot reload)
      - .:/app
      # Preserve node_modules in container
      - /app/node_modules
      # Persist database
      - ./prisma:/app/prisma
    networks:
      - car-rental-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/test-env"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  car-rental-network:
    driver: bridge
